# -*- coding: utf-8 -*-
"""Q3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCV2KLr72RCCnOrSsiFi2gBEXWx3Wqd5
"""

import pandas as pd
df = pd.read_csv("/content/products.csv")

print("\n--- Product List ---")
for index, row in df.iterrows():
    print(f"ID: {row['product_id']}, Name: {row['product_name']}, "
          f"Category: {row['category']}, Price: {row['price']}, Quantity: {row['quantity']}")

total_rows = len(df)
print("\nTotal number of rows:", total_rows)

above_500 = df[df['price'] > 500]
print("Products priced above 500:", len(above_500))

avg_price = df['price'].mean()
print("Average price of all products:", avg_price)

category_input = input("\nEnter a category to filter: ")
filtered = df[df['category'].str.lower() == category_input.lower()]

print(f"\nProducts in category '{category_input}':")
if filtered.empty:
    print("No products found in this category.")
else:
    for index, row in filtered.iterrows():
        print(f"- {row['product_name']} (Price: {row['price']}, Qty: {row['quantity']})")

total_quantity = df['quantity'].sum()
print("\nTotal quantity of all items in stock:", total_quantity)